from question import Question

question1 = Question("Kuhu läheb Coca Cola purk?", "metall ja plastik", "Coca Cola purk käib metalli ja plastiku hulka")
question2 = Question("Kuhu läheb krõpsupakk?", "metall ja plastik", "Krõpsupakk käib metalli ja plastiku hulka")
question3 = Question("Kuhu läheb piimapakk?", "metall ja plastik", "Piimapakk käib metalli ja plastiku hulka")
question4 = Question("Kuhu läheb jogurtipakk?", "metall ja plastik", "Jogurtipakk käib metalli ja plastiku hulka")
question5 = Question("Kuhu lähevad ravimid?", "ohtlikud jäätmed", "Ravimid käivad ohtlike jäätmete hulka")
question6 = Question("Kuhu lähevad patareid?", "ohtlikud jäätmed", "Patareid käivad ohtlike jäätmete hulka")
question7 = Question("Kuhu läheb banaani koor?", "biojäätmed", "Banaani koor käib biojäätmete hulka")
question8 = Question("Kuhu läheb pehme mänguasi?", "olmejäätmed", "Pehme mänguasi käib olmejäätmete hulka")
question9 = Question("Kuhu läheb nõudepesu vahendi pudel?", "metall ja plastik", "Nõudepesu vahendi pudel käib metalli ja plastiku hulka")
question10 = Question("Kuhu läheb raamat?", "papp ja paber", "Raamat käib papp ja paberi hulka")
question11 = Question("Kuhu läheb arvuti hiir?", "jäätmejaam", "Arvuti hiir käib jäätmejaama")
question12 = Question("Kuhu läheb nuudlipakk?", "metall ja plastik", "Nuudlipakk käib metalli ja plastiku hulka")
question13 = Question("Kuhu läheb huulepulk?", "olmejäätmed", "Huulepulk käib olmejäätmete hulka")
question14 = Question("Kuhu läheb klaaspurk?", "klaas", "Klaaspurk käib klaasi konteinerisse")
question15 = Question("Kuhu läheb vana t-särk?", "riide konteiner", "Vana t-särk käib riiete konteinerisse")
question16 = Question("Kuhu läheb pooleldi söödud õun?", "biojäätmed", "Pooleldi söödud õun käib biojäätmete hulka")
question17 = Question("Kuhu läheb pastakas?", "olmejäätmed", "Pastakas käib olmejäätmete hulka")
question18 = Question("Kuhu läheb kalkulaator?", "jäätmejaam", "Kalkulaator käib jäätmejaama")
question19 = Question("Kuhu läheb päevavalguse lambi pirn?", "olmejäätmed", "Päevavalguse lambi pirn käib olmejäätmete hulka")
question20 = Question("Kuhu läheb rattavelg?", "jäätmejaam", "Rattavelg käib jäätmejaama")
